### ISSUE TITLE
length of expert

### ISSUE THREAD

**Issue by fugo** [getgrav/grav-theme-notepad#12]
Where can I find the place to change the length of the text under the blog title:

![](https://i.imgur.com/d8fPPfH.png)

Sorry I don't find it.

**Comment by BirdKeyboard** [comment]
Hi @fugo ! I've submitted a pull request that adds a theme configuration option. If you don't want to wait for it to be approved you can change the truncate value in `notepad/templates/partials/article.html.twig` on line 23

Pull request: #15
