### ISSUE TITLE
Font-awesome icons not showing

### ISSUE THREAD

**Issue by jkelleher** [getgrav/grav-theme-notepad#2]
On my hosting, I'm having a problem seeing the Font Awesome icons. I'm getting empty squares with some code inside. I've fixed the problem by removing the FA assets.addCss() and replacing with a direct reference to the maxcdn file:

```
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
```

Obviously, this drops the CSS from the pipeline which hits performance so I'm curious to figure out what the real root of the problem is.
I did replace the packaged font-awesome.min.css with the contents from the CDN but that didn't fix it.

**Comment by hexplor** [comment]
Hello,
I apologize for delay in replying. Is it possible that you provide me link to your website where i can check that FontAwesome error ? I double tested on my install with newest grav and it works without issues.

**Comment by jkelleher** [comment]
@hexplor Thanks Karol for getting in touch. It was on a site for my daughter (www.siofrakelleher.com) where I encountered the problem. I've checked (in devTools) that the fix mentioned is still in place but I don't have access (right now) to the repo to check what prompted me to put that fix in place.
I'll see if I can get hold of the code later and get back to you but maybe you can tell something from the site. Thanks again. J

**Comment by hexplor** [comment]
Well, on website above FontAwesome icons are loaded in standard way, through assets.addCss(), and they load fine, so i guess everything appears to work, or you have specific page where it does not work ?

**Comment by jkelleher** [comment]
@hexplor Great thanks again.
