### ISSUE TITLE
"tags" page not found

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-theme-notepad#6]
There's a bug with tags on the Notepad demo site. For example, on this page:

http://demo.getgrav.org/notepad-skeleton/blog/2014-11-30-why-grav

click on a tag below the title, for example _theme_. The resulting page (http://demo.getgrav.org/tags/index.html#theme) is not found.

About this bug, [rhukster wrote](http://getgrav.org/forum#!/general:foundation-demo-link-broken/i-would-say-a-bug-with-the):

> I would say a bug with the notepad theme, the skeleton just is a package of pages + plugins + theme. But the theme is the part that renders the tags

**Comment by siren386** [comment]
This happens also on the downloaded skeleton, the link for the tags from within the articles is set to " #tag " but does not contain a complete link.

**Comment by kennedyabitbol** [comment]
Hi, it also happend with the last version, is there any redirection not available in the config?

**Comment by flaviocopes** [comment]
I don't see any problem in the skeleton http://demo.getgrav.org/notepad-skeleton/tag:theme

**Comment by kennedyabitbol** [comment]
In my case, it redirect to the homepage
