### ISSUE TITLE
Date/article overlapping menu in lower resolutions

### ISSUE THREAD

**Issue by siren386** [getgrav/grav-theme-notepad#7]
When opening the notepad-skeleton on a mobile device an then open the menu, the date of an article as well as the icons for facebook, twitter and so on overlap the menu.

**Comment by siren386** [comment]
Hi!

Thanks for the fix, the menu isn`t overlapping anymore. But, on mobile devices in my opinion it looks a little ugly now, because there is now big spacing between logo and menu-button and menu button and header ...

**Comment by hexplor** [comment]
can you make a screenshot ? It looks fine on my install.
