### ISSUE TITLE
No way to remove the RSS feed?

### ISSUE THREAD

**Issue by LieutenantRice** [getgrav/grav-theme-notepad#9]
Hey guys, this is a great theme but I can not for the life of me find a way to remove the feed menu on the site. I've spent 2 hours looking through files and admin settings and have come up with nothing. Really starting to feel incapable and thought I'd ask.

Thanks.

**Comment by OleVik** [comment]
Do you mean the link to the RSS-feed on the menu itself? That can be removed from the navigation-template partial, ie. [here](https://github.com/getgrav/grav-theme-notepad/blob/develop/templates/partials/navigation.html.twig#L18). Just remove the line entirely or comment it out like this: `{# <li><a href="{{ base_url }}/blog.rss" title="Atom/RSS feed"><i class="icon-rss"></i> Feed</a></li> #}`.

**Comment by LieutenantRice** [comment]
Yes that was it!! Thank you so much, It's still my first day with Grav. :)

**Comment by flaviocopes** [comment]
A method I use is to open the user/ folder in Sublime Text or other text editor, and search a particular string of text (or HTML markup) I see in the page, from there you'll get to the place that generates it.

When you edit the theme files, a theme update will overwrite them. So, next step is learn about theme inheritance :) https://learn.getgrav.org/themes/customization#theme-inheritance
